const AUTH_USER_LOADING_GOOGLE_ACCOUNTS = 'AUTH_USER_LOADING_GOOGLE_ACCOUNTS'
const AUTH_USER_SUCCESS_WITH_GOOGLE_ACCOUNT =
  'AUTH_USER_SUCCESS_WITH_GOOGLE_ACCOUNT'
const AUTH_USER_ERROR_WITH_GOOGLE_ACCOUNT =
  'AUTH_USER_ERROR_WITH_GOOGLE_ACCOUNT'
const AUTH_USER_SIGNOUT_FROM_ACCOUNT = 'AUTH_USER_SIGNOUT_FROM_ACCOUNT'
const AUTH_USER_SAVE_DATA_ACCOUNT_IN_STORAGE =
  'AUTH_USER_SAVE_DATA_ACCOUNT_IN_STORAGE'

const LOAD_MESSAGES_TO_STORE_SUCCESS = 'LOAD_MESSAGES_TO_STORE_SUCCESS'
const LOAD_MESSAGES_TO_STORE_ERROR = 'LOAD_MESSAGES_TO_STORE_ERROR'
const LOAD_MESSAGES_TO_STORE_REQUEST = 'LOAD_MESSAGES_TO_STORE_REQUEST'

const variableWithAuthUserAndSignOut = ['load', 'auth', 'error', 'signout']

export { variableWithAuthUserAndSignOut }

export {
  AUTH_USER_LOADING_GOOGLE_ACCOUNTS,
  AUTH_USER_SUCCESS_WITH_GOOGLE_ACCOUNT,
  AUTH_USER_ERROR_WITH_GOOGLE_ACCOUNT,
  AUTH_USER_SIGNOUT_FROM_ACCOUNT,
  AUTH_USER_SAVE_DATA_ACCOUNT_IN_STORAGE,
  LOAD_MESSAGES_TO_STORE_ERROR,
  LOAD_MESSAGES_TO_STORE_REQUEST,
  LOAD_MESSAGES_TO_STORE_SUCCESS,
}
